language: elixir

elixir:
  - 1.9

otp_release:
  - 22.0

env:
  - MIX_ENV=test

script:
  - mix test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix compile

after_script:
  - MIX_ENV=test mix coveralls.travis
  - MIX_ENV=docs mix deps.get
